### ISSUE TITLE
Pip install not working properly

### ISSUE THREAD

**Issue by arzaatri** [Asugawara/requests-html-playwright#21]
After pip installing this package `pip install requests-html-playwright` and trying to import HTMLSession, I got this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'HTMLSession' from 'requests_html_playwright' (C:\Users\arzaa\miniconda3\envs\music\Lib\site-packages\requests_html_playwright\__init__.py)
```

I checked the specified file and found that it was blank.

Can be manually fixed by copying the contents of that same file from this repo

**Comment by Asugawara** [comment]
Thank you for reporting the issue!
The issue has been resolved in the latest release!
